export enum CategoriesActionTypes {
  FETCH_CATEGORIES = 'FETCH_CATEGORIES',
  SELECT_CATEGORY = 'SELECT_CATEGORY',
  FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS',
  FETCH_CATEGORIES_ERROR = 'FETCH_CATEGORIES_ERROR',
}
