export enum TableOrderActionTypes {
  FETCH_TABLE_ORDER = 'FETCH_TABLE_ORDER',
  FETCH_TABLE_ORDER_SUCCESS = 'FETCH_TABLE_ORDER_SUCCESS',
  FETCH_TABLE_ORDER_ERROR = 'FETCH_TABLE_ORDER_ERROR',
  SET_TABLE_ORDER_PAGE = 'SET_TABLE_ORDER_PAGE',
}
